function Hd = lowpassfilter(Fpass_,Fstop_)
%LOWPASSFILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.6 and the Signal Processing Toolbox 7.1.
% Generated on: 06-Oct-2016 15:19:19

Fpass = Fpass_;  % Passband Frequency
Fstop = Fstop_;  % Stopband Frequency
Apass = 0.1;     % Passband Ripple (dB)
Astop = 70;    % Stopband Attenuation (dB)

h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop);

Hd = design(h, 'equiripple', ...
    'MinOrder', 'any', ...
    'StopbandShape', 'flat');



